//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HopDongs = new HashSet<HopDong>();
            this.TTBaoHiems = new HashSet<TTBaoHiem>();
            this.TTChamCongs = new HashSet<TTChamCong>();
        }
        [Display(Name = "Mã Nhân Viên")]
        public int IdNV { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }
        [Display(Name = "Email/Gmail")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ! Vui lòng kiểm tra lại")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [Display(Name = "Mật Khẩu")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Display(Name = "Có là admin?")]
        public Nullable<bool> IsAdmin { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [Display(Name = "Số Điện Thoại")]
        [RegularExpression("^(?!0+$)(\\+\\d{1,3}[- ]?)?(?!0+$)\\d{10,15}$", ErrorMessage = "Vui lòng nhập đúng định dạng số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Giới Tính(Nam)")]
        public Nullable<bool> GioiTinh { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Ngày Sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Display(Name = "Quê Quán")]
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        public string QueQuan { get; set; }
        [Display(Name = "Dân Tộc")]
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        public string DanToc { get; set; }
        [Display(Name = "Phòng Ban")]
        public int IdPB { get; set; }
        [Display(Name = "Chức Vụ")]
        public int IdCV { get; set; }
        [Display(Name = "Phụ Cấp")]
        public Nullable<int> IdPC { get; set; }
        [Display(Name = "Trình Độ Học Vấn")]
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        public string TrinhDoHV { get; set; }

        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTBaoHiem> TTBaoHiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTChamCong> TTChamCongs { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual PhuCap PhuCap { get; set; }
    }
}