//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhuCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhuCap()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
        [Display(Name = "Mã Phụ Cấp")]
        public int IdPC { get; set; }
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [Display(Name = "Tên Phụ Cấp")]
        public string TenPC { get; set; }
        [Display(Name = "Tiền Phụ Cấp(1000VNĐ)")]
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Chỉ được nhập số!")]
        public Nullable<double> TienPC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}