//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TTChamCong
    {
        [Display(Name = "Mã Chấm Công")]
        public int IdCC { get; set; }
        [Display(Name = "Nhân Viên")]
        public Nullable<int> IdNV { get; set; }
        [Display(Name = "Ngày Chấm Công")]
        [Required(ErrorMessage = "Vui lòng không bỏ trống trường này!")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayCC { get; set; }
        [Display(Name = "Thời Gian Vào")]
        public Nullable<System.TimeSpan> TVao { get; set; }
        [Display(Name = "Thời Gian Ra")]
        public Nullable<System.TimeSpan> TRa { get; set; }
        [Display(Name = "Vi Phạm")]
        public Nullable<bool> ViPham { get; set; }

        public virtual NhanVien NhanVien { get; set; }
    }
}
